### ISSUE TITLE
Investiguer et intégrer l'espace doc de laclasse.com dans l'espace ressources CCNs

### ISSUE THREAD

**Issue by pvincent4** [ccnum/plugin_thematique_laclasse#106]

**Comment by heleroy** [comment]
J'ai vu avec Daniel et c'est tout à fait possible et il est ravi de proposer cette solution : aussi bien un lien vers l'espace docs qui pointe directement sur l'espace du groupe libre, et c'est aussi possible d'afficher les docs (pointé sur le groupe libre) comme la fenêtre scratch sur Code (ou la carte umap sur Habiter). De plus, ça permettrait de faire du cliquer-glisser-déposer des fichiers vidéos directement dans le dossier du groupe libre qui apparaît sur le site CCN. On pourra ouvrir/lire les fichiers vidéos dans un nouvel onglet en double cliquant dessus (et non pas sur une pop-up du site SPIP - CCN) mais ça ne doit pas être gênant pour l'utilisateur. Il faudra faire des tests pour vérifier que l'aperçu de l'espace docs n'est pas trop moche dans une petite fenêtre.
