### ISSUE TITLE
Fichiers .hex ?

### ISSUE THREAD

**Issue by racine-p-a** [ccnum/plugin_thematique_laclasse#130]

**Comment by racine-p-a** [comment]
Requiert de modifier le plugin forum.
Nécessaire?

**Comment by cmonnet** [comment]
Les classes commencent à publier leurs réponses, les élèves doivent pouvoir partager des fichiers .hex via le forum, tu peux échanger avec Sébastien Albert sur le sujet : contact@studio-albert.com

**Comment by racine-p-a** [comment]
Résolution :
- ajout de l'acceptation des fichiers .hex dans le forum -> ne semble pas fonctionner car fichiers .hex inconnus de SPIP
- ajout d'une ligne dans la base de données du site (table code_types_documents) (utilisateur et mot de passe dans les fichiers internes de SPIP (connect.php)
