### ISSUE TITLE
bug d'affichage sur Firefox et Safari pour modifier un article

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_thematique_laclasse#134]
Sur Firefox à jour, le bouton annuler / enregistrer n'apparait pas si on est sur un petit écran d'ordi portable (pas de bug sur nos écrans en 25 pouces car on peut voir toute la fenêtre ;) )
Sur Safari, on ne peut même pas voir le crayon vert pour modifier un article.
 capture sur Firefox : ![Capture du 2019-10-02 11-48-42](https://user-images.githubusercontent.com/7963908/66035006-9bedd700-e50a-11e9-88cf-9ca68a9dc088.png)
![chrome](https://user-images.githubusercontent.com/7963908/66035137-e40cf980-e50a-11e9-9a5f-528ae378049d.png)
Sur Chrome on voit le bouton mais la fenêtre de saisie est très petite par défaut.

**Comment by pvincent4** [comment]
C'est la première fois que je vois celà

**Comment by racine-p-a** [comment]
Bug provenant du plugin crayons et qui entrait en multi-conflits avec les différentes feuilles de style.
Corrigé mais au prix d'une certaine propreté du design (décentrage).
