### ISSUE TITLE
Rétablir Années archivées sur CCN AIR

### ISSUE THREAD

**Issue by cmonnet** [ccnum/plugin_thematique_laclasse#153]
Le sélecteur d'année archivées du projet CCN AIR ne fonctionne plus, lorsqu'on sélectionne une année antérieure du projet cela ne dirige pas sur l'année archivée en question : https://air.laclasse.com/spip.php?page=sommaire

**Comment by racine-p-a** [comment]
Remise en place mais en désactivant le plugin thématique sur `airchives` pour cause d'obsolescence.
- https://github.com/ccnum/plugin_air_laclasse/commit/4ade5c2388d1130f0d6967b488d23a8523375b8a
- https://github.com/ccnum/plugin_air_laclasse/commit/3ad405456bc20a38f4f98e5e8091ead45c9d47c1
- https://github.com/ccnum/plugin_air_laclasse/commit/ec8c4a9b2a0669581327ecb77f648b4398e941ce
