### ISSUE TITLE
CCN FICTIONS : Script indisponible

### ISSUE THREAD

**Issue by Hunerva** [ccnum/plugin_thematique_laclasse#161]
Pour un utilisateur hors administrateur, les documents dans les scripts ne sont pas visibles/disponibles alors qu'ils ont bien été téléversés.
Ce bug apparait seulement pour les réponses après la première publication de chaque colonne. Les documents présents dans les scripts des premières publications (par Marc Alexandre) sont bien consultables.

**Comment by racine-p-a** [comment]
Corrigé en affichant par défaut toutes les images.
Une correction propre de ce bug nécessiterait une réécriture d'une grosse portion de code.
