### ISSUE TITLE
Utilisation de <seq_posy_consignes> dans projet.xml

### ISSUE THREAD

**Issue by kevinvennitti** [ccnum/plugin_thematique_laclasse#35]
Chaque consigne semble disposer de son propre Y dans sa déclaration XML (consignes.xml), est-ce que les multiples valeurs de <seq_posy_consignes> dans projet.xml servent toujours ?

**Comment by pvincent4** [comment]
Elles ont une valeur par défaut qui est surchargée par une valeur en BDD si elles ont été déplacées à la main (en cas de superposition)
