### ISSUE TITLE
Vérifier si la fenêtre de requête par année scolaire peut être gérée par une pipeline

### ISSUE THREAD

**Issue by pvincent4** [ccnum/plugin_thematique_laclasse#36]

**Comment by kevinvennitti** [comment]
À priori, ce n'est pas si simple, car la récupération des données (ARTICLES, RUBRIQUES, etc) ne se fait pas de la même manière : on compare #DATE pour les ARTICLES, mais il faut bidouiller avec les rubriques d'archivage pour cibler une RUBRIQUE (comme les classes courantes).
