### ISSUE TITLE
Ajouter les logos institutionnels

### ISSUE THREAD

**Issue by pvincent4** [ccnum/plugin_thematique_laclasse#41]
Métropole, Erasme, Logo territoire innovants-
Sur master et dev

**Comment by kevinvennitti** [comment]
Logos à placer où ?

**Comment by pvincent4** [comment]
Dans la version historique, en haut dans la barre de menu.
Dans la nouvelle version, ancrée en bas en alignement horizontal avec les autres outils.
Il faudra faire quelques tests, mais pour la version actuelle on basculera en prod dès la rentrée.
