### ISSUE TITLE
Optimiser la navigation à deux colonnes (ex : vues ressources / classes)

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_thematique_laclasse#63]
Depuis la refonte des sites CCN c'est le seul endroit où, au contraire, on a plus de clic s à faire pour naviguer d'une ressource à une autre. Avant, on avait l'arborescence des ressources qui continuait d’apparaître quand on visualisait une ressource.

**Comment by pvincent4** [comment]
En première intention, tester d'ouvrir en d'ouvrir cette vue directement sur deux colonnes (mode plein écran)

**Comment by pvincent4** [comment]
A qualifier plus précisément
