### ISSUE TITLE
Affichage 2 colonnes / Vue classe : mettre en premier bloc la rubrique adéquate

### ISSUE THREAD

**Issue by pvincent4** [ccnum/plugin_thematique_laclasse#76]
- soit le collège est connecté : on mets sa rubrique en haut
- soit on est pas connecté : on mets la rubrique mère de l'article en haut

A consolider

**Comment by pvincent4** [comment]
@ebau Pouvez vous compléter votre vision sur ce point

**Comment by Pipazoul** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#Issue 76](https://trello.com/c/5n4iRsus/4-issue-76)
