### ISSUE TITLE
Lorsqu'un article est supprimé,il continue d’apparaître dans le cadre des de la page "Toutes les classes"

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_thematique_laclasse#82]
(en bas de la timeline). C'est gênant, après une séance de formation sur les CCN, malgré le ménage de fait sur le site, les actus affichent encore les articles de tests...

**Comment by Pipazoul** [comment]
Après vérification avec @heleroy, ce bug ne semble pas présent

**Comment by Pipazoul** [comment]
Est présent dans la page "Toutes les classe"
Affiche les articles avec le statut "poubelle"
