### ISSUE TITLE
Modifier l'échelle de la timeline sur la vue de la consigne selon les cas

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_thematique_laclasse#91]
![consigne 14-18](https://user-images.githubusercontent.com/7963908/38301676-93884216-3800-11e8-8a4b-41e6d56d84f2.PNG)
en fonction de l'écart de temps entre la consigne et les réponses, et selon la taille de l'écran que l'on utilise, on ne voit pas les vignettes des réponses, ou c'est la vignette de la consigne qui disparait à gauche de l'écran.  cf capture

**Comment by pvincent4** [comment]
On ne réussit pas à reproduire, tu peux préciser le contexte (navigateur, résolution, etc) ?

**Comment by heleroy** [comment]
Je ne reproduis plus non plus donc ça a dû se régler tout seul je pense. J'étais sur Chrome (à jour) quand j'avais fait les tests. C'était sur la dernière consigne de cette année pour 14-18.
