### ISSUE TITLE
[Commentaire - Forum] Bloquer la possibilité de s'incrire sur le forum

### ISSUE THREAD

**Issue by ebau** [ccnum/plugin_thematique_laclasse#93]
Lorsqu'on clique sur "Commenter", en étant seulement visiteur, on nous propose de se connecter ou bien de s'inscrire, ou faire un mot de passe oublié. Il faudrait donc supprimer l'option 2 "s'inscrire" pour éviter tout débordement (1 cas cette année sur le projet ccnencyclopedie)

![forum - inscription](https://user-images.githubusercontent.com/29462321/38314299-22df42b4-3826-11e8-855c-46681d7b2e36.png)

**Comment by pvincent4** [comment]
Problématique sur SPIP à mon avis car option de gestion choisie > simplement ne pas afficher le lien
